config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  # devise_for :user, :path => "accounts"

  # root 'devise/sessions#new', as: :unauthenticated_root
#  devise_for :users
  devise_for :users, paths:'users', :controllers => { registrations: 'registrations' }
  resources :welcome, only: :index
  # root 'welcome#index'
  resources :about, only: :index
  # root 'about#index'

  resources :dashboard, only: [:index,:edit]
  authenticated :user do
  root "dashboard#index", as: :authenticated_root
    end
  unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
  end


  # devise_scope :user do
  #   authenticated :user do
  #     root 'home#index', as: :authenticated_root
  #   end
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end

  resources :users, only: [:index], shallow:true do
    resources :recipes, only: [:new,:create,:index]
  end

  resources :recipes, only: [:show,:edit,:update,:destroy] do
      resources :comments, only: [:new,:create]
  end

  resources :comments, only: :destroy
  resources :allergies, only: :index
  resources :foodflags, only: :index
  resources :ingredientflags, only: :index

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :ingredientflags
  has_attached_file :picture, styles: { medium: "270x270>", thumb: "100x100>" }, :default_url => "1908bowlMeascupSpoon.png"

   ratyrate_rateable "title"
  # validates_attachment_content_type :picture, :content_type => ["picture/jpg", "picture/jpeg", "picture/png", "picture/gif"]
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  validates :title, :ingredients, :directions, presence: true, length: { minimum: 3}

  validates :user_id, presence: true

  GROUPS = %w{ appetizer breakfast dessert entree salad side_dish snack soup other }
  validates :category, inclusion: {in: GROUPS, message: 'is Invalid'}

  def self.filter(user)
    user_ingreds = user.allergies.map{|allergy| allergy.ingredientflag_ids}.flatten
    out = [];
    Recipe.all.map do |rec|
      user_ingreds.each {|id| out << rec if  rec.ingredientflag_ids.include?(id) }
    end
    Recipe.all - out
  end

  def find_allergens
    @allergens = []
    self.ingredientflags.each do |id|
      @allergens << Ingredientflag.find(id).allergies.first.name
    end
    @allergens.uniq!
    @allergens.length > 0 ? @allergens.join(", ") : "none"
  end

  def flagged_ingredients
    @recipe_flags_ids = []
    @temp_ingredients = self.ingredients.downcase
    @ingredientflags = Ingredientflag.all.sort_by {|ingredient| ingredient.name.length}.reverse

    @ingredientflags.each do |ingredientflag|
      if @temp_ingredients.include?(ingredientflag.name.downcase)
           @temp_ingredients.sub(ingredientflag.name.downcase," ")
          @recipe_flags_ids << ingredientflag.id

      end
    end
    return @recipe_flags_ids
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user, only: [:index, :new, :create]
  before_action :set_recipe, only: [:edit, :update, :destroy, :show]

  def index
    @recipes = @user.recipes
    @filter_recipes = Recipe.filter(current_user)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @current_user = current_user
    @ingredients = split_ingredients
    @allergens = @recipe.find_allergens
    @rating_exist = rating_exist.nil? ? false : true
    @rating_for_user = rating_exist_user ? true : false

  end

  def create
    byebug;
    @recipe = @user.recipes.new(recipe_params)
    @recipe_flagged = @recipe.flagged_ingredients()
    @recipe.ingredientflag_ids = @recipe_flagged unless @recipe_flagged.empty?
    byebug;
    if @recipe.save
      flash[:success] = 'Recipe successfully created.'
      redirect_to user_recipes_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'Recipe successfully saved.'
      redirect_to user_recipes_path(@recipe.user_id)
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      flash[:success] = 'Recipe successfully destroyed.'
      redirect_to user_recipes_path(@recipe.user_id)
    else
      flash[:error] = 'Failed to destroy recipe.'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def split_ingredients
    @recipe.ingredients.split(',')
  end

  def rating_exist
    Rate.all.find_by(rateable_id: params[:id])
  end

  def rating_exist_user
    flag = false
    filteredRates = Rate.all.where(rateable_id: params[:id])
    temp = filteredRates.map{|rate| rate.rater_id==current_user.id ? flag =true : 0}
    return flag
  end

  def recipe_params
    params.require(:recipe).permit(:picture, :title, :ingredients, :category, :directions, :user_id, ingredientflag_ids:[])
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%=form_for [@user, @recipe], :html =>{ :multipart =>true } do |f| %>
  <div class='field'>
    <%=f.label :title %><br>
    <%=f.text_field :title %>
  </div>

  <div class='field'>
    <%=f.label :category %><br>
    <%=f.select :category, %w{ appetizers breakfast dessert entree salads side_dishes snacks soup other }, :prompt=>'Food Category', :size=>50 %>
  </div>

  <div class='field'>
    <%=f.label :ingredients %><br>
    <%=f.text_area :ingredients, placeholder: "Please seperate ingredients with a , (comma). Example: 1 cup sugar, 2 tbs corn starch, 2 cups flour",cols:60, rows:4%>
  </div>

   <div class='field'>
    <%=f.label :directions %><br>
    <%=f.text_area :directions, placeholder: "Please seperate steps with a number). Example: 1) Preheat oven to 300F. 2) Mix ingredients. 3) Place in oven.", cols:60, rows:6 %>
  </div>
  <strong>Choose a Picture File</strong><br>
   <%= f.file_field :picture %>
   <br>
    <div class="actions">
      <%= f.submit "Save Recipe", class: 'btn btn-primary btn-lg' %>
    </div>

<% end %>

app/views/recipes/_recommend.html.erb
<h2>Recommended Recipes</h2>
<table>
  <thead>
    <tr>
      <th><span class="glyphicon glyphicon-link"></span>Title</th>
      <th>Category</th>
      <th>Rating</th>
      <th>Submittal Date</th>
    </tr>
  </thead>

  <tbody>
    <%@filter_recipes.each do |recipe|%>
      <tr>
        <td><%=link_to recipe.title.titleize, recipe_path(recipe.id)%></td>
        <td><%=recipe.category%></td>
        <td><%if recipe.rates("title").count > 0%>
             <%=recipe.average("title").avg.round(1)%><img src="/assets/star-on.png">
            <%else%>
              <%= rating_for recipe, "title", disable_after_rate: true %><%end%></td>
        <td><%= recipe.created_at.month%>/<%= recipe.created_at.year%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<div class='container-fluid height-full'>
  <div class="row">
    <div class="col-xs-2 col-sm-3">
      <div class="sidebar">
        <h3><%=current_user.name ? current_user.name.titleize + '\'s' : Your%> Account</h3>
        <ul>
          <li><a href="/dashboard"><span class="glyphicon glyphicon-dashboard"></span>Dashboard</a></li>
          <li><a href="/users/<%=current_user.id%>/recipes"><span class="glyphicon glyphicon-folder-open"></span>View/Edit Submitted Recipes</a></li>
          <li><a href = "/users/<%=current_user.id%>/recipes/new"><span class="glyphicon glyphicon-cutlery"></span>Submit New Recipe </li>
          <li><a href="/users/edit"><span class="glyphicon glyphicon-cog"></span>Account Info</a> </li>
          <li><em>Current Allergies </em>
           <% current_user.allergies.each do |allergy| %>
            <em>&nbsp; &#149;<%=allergy.name %></em>
            <%end%></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-xs-10 col-sm-9">
      <h2>Edit Recipe</h2>
      <%= render 'form'%>
      <br>
      <div class='btn btn-warning btn-lg'><%= link_to 'DELETE Recipe', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?' } %></div>
   </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-xs-2 col-sm-3">
      <div class="sidebar">
        <h3><%=@current_user.name ? @current_user.name.titleize + '\'s' : Your%> Account</h3>
        <ul>
          <li><a href="/dashboard"><span class="glyphicon glyphicon-dashboard"></span>Dashboard</a></li>
          <li><strong><span class="glyphicon glyphicon-folder-open"></span>View/Edit Submitted Recipes</strong></li>
          <li><a href = "recipes/new"><span class="glyphicon glyphicon-cutlery"></span>Submit New Recipe </li>
          <li><a href=" /users/edit"><span class="glyphicon glyphicon-cog"></span>Account Info</a> </li>
          <li><em>Current Allergies </em>
           <% @current_user.allergies.each do |allergy| %>
            <em>&nbsp; &#149;<%=allergy.name %></em>
            <%end%></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  <div class="col-xs-10 col-sm-9">
<h2><%=current_user.name ? current_user.name.titleize+' ' : You+' '%>Submitted Recipes</h2>
  <div class='recipe_links'>
    <ul>
      <%@recipes.each do |recipe|%>
      <li><%= link_to edit_recipe_path(recipe), class: "btn btn-default" do %>  <i class="glyphicon glyphicon-edit">Edit</i><%end%>
        <%=link_to recipe.title.titleize, recipe_path(recipe.id)%></li>
      <%end%>
    </ul>
  </div>
</div>

app/views/recipes/new.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-xs-2 col-sm-3">
      <div class="sidebar">
        <h3><%=current_user.name ? current_user.name.titleize + '\'s' : Your%> Account</h3>
        <ul>
          <li><a href="/dashboard"><span class="glyphicon glyphicon-dashboard"></span>Dashboard</a></li>
          <li><a href="/users/<%=current_user.id%>/recipes"><span class="glyphicon glyphicon-folder-open"></span>View/Edit Submitted Recipes</a></li>
          <li><strong><span class="glyphicon glyphicon-cutlery"></span>Submit New Recipe</strong> </li>
          <li><a href="/users/edit"><span class="glyphicon glyphicon-cog"></span>Account Info</a> </li>
          <li><em>Current Allergies </em>
           <% current_user.allergies.each do |allergy| %>
            <em>&nbsp; &#149;<%=allergy.name %></em>
            <%end%></li>
        </ul>
      </div>
    </div>
    <div class="col-xs-10 col-sm-9">
    <h2>Create New Recipe</h2>
<%= render 'form'%>
  </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-sm-3">
      <div class="sidebar">
        <h3><%=current_user.name ? current_user.name.titleize + '\'s' : Your%> Account</h3>
        <ul>
          <li><a href="/dashboard"><span class="glyphicon glyphicon-dashboard"></span>Dashboard</a></li>
          <li><a href="/users/<%=current_user.id%>/recipes"><span class="glyphicon glyphicon-folder-open"></span>View/Edit Submitted Recipes</a></li>
          <li><a href = "/users/<%=current_user.id%>/recipes/new"><span class="glyphicon glyphicon-cutlery"></span>Submit New Recipe </li>
          <li><a href=" /users/edit"><span class="glyphicon glyphicon-cog"></span>Account Info</a> </li>
          <li><em>Current Allergies </em>
           <% @current_user.allergies.each do |allergy| %>
            <em>&nbsp; &#149;<%=allergy.name %></em>
            <%end%></li>
        </ul>

      </div>
    </div>
    <div class="col-sm-3">
    <section>
    <%= image_tag @recipe.picture.url(:medium) %>
    </div>
    <div class="col-sm-6">
      <h1 id="title"><%=@recipe.title.titleize%></h1>
      <ul>
        <li><%if @rating_exist %>
             <h3><%=@recipe.average("title").avg.round(1)%><img src="/assets/mid-star.png"></h3>
            <%else%>
              <%= rating_for @recipe, "title", disable_after_rate: true %><%end%>
        </li>
        <li>Total Votes: <%= @recipe.rates("title").count %></li>
        <li>Category: <%=@recipe.category.titleize%></li>
        <li>Created/Submitted By: <%=User.find(@recipe.user_id).name.titleize%></li>
        <li>Submittal Date: <%= @recipe.created_at.month%>/<%= @recipe.created_at.year%></li>
        <li><em>Allergens: <%=@allergens%></em></li>
        <li><% if current_user == User.find(@recipe.user_id)%>
            <%= link_to edit_recipe_path(@recipe), class: "btn btn-default" do %>  <i class="glyphicon glyphicon-edit">Edit</i>
            <%end%>
            <%end%>
        </li>
        <%if !@rating_for_user %>
          <li>Add Your Vote<%=rating_for @recipe, "title", disable_after_rate: true %></li><%end%>
      </ul>
    </div>
    </section>
  </div>

   <div class = 'row'>
      <div class="col-sm-3">
        <%= render '/comments/form'%>
      </div>
    <div class='col-sm-3'>
      <ul><h3>Ingredients</h3>
      <% @ingredients.each do |ingredient|%>
        <li><%=ingredient%></li>
        <%end%>
      </ul>
    </div>
    <div class='col-sm-6'>
     <h3> Directions</h3> <%=@recipe.directions%>
    </div>
  </div>
    <div class = 'row'>
      <div class='col-sm-9 col-sm-offset-3'>
      <div class='notes_header'><h3 >Comments</h3>
      </div> <ul>
        <% if @recipe.comments.size > 1 %>
          <li class='notes'><%= render @recipe.comments%></li>
          <%end%>
        </ul>
        </div>
         </div>
      </div>
     </div>
    </div>