config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  # devise_for :user, :path => "accounts"

  # root 'devise/sessions#new', as: :unauthenticated_root
#  devise_for :users
  devise_for :users, paths:'users', :controllers => { registrations: 'registrations' }
  resources :welcome, only: :index
  # root 'welcome#index'
  resources :about, only: :index
  # root 'about#index'

  resources :dashboard, only: [:index,:edit]
  authenticated :user do
  root "dashboard#index", as: :authenticated_root
    end
  unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
  end


  # devise_scope :user do
  #   authenticated :user do
  #     root 'home#index', as: :authenticated_root
  #   end
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end

  resources :users, only: [:index], shallow:true do
    resources :recipes, only: [:new,:create,:index]
  end

  resources :recipes, only: [:show,:edit,:update,:destroy] do
      resources :comments, only: [:new,:create]
  end

  resources :comments, only: :destroy
  resources :allergies, only: :index
  resources :foodflags, only: :index
  resources :ingredientflags, only: :index

end

app/models/ingredientflag.rb
class Ingredientflag < ActiveRecord::Base
  has_many :foodflags
  has_many :allergies, through: :foodflags
  has_and_belongs_to_many :recipes

  validates :name, presence: true
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @allergies = Allergy.all
  end

end

app/views/welcome/_form.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-sm-11 col-sm-1">
    <h1> Sign In </h1>
    </div>
  </div>
  <%= form_for(:user, :url => session_path(:user)) do |f| %>
    <div class="row">
      <div class="col-sm-11 col-sm-offset-1">
        <%= f.text_field :email, placeholder: "Login Email", size: 30 %>
        <%= f.password_field :password, placeholder: "Password", size: 30 %>
        <%= f.submit 'Sign in', class: 'btn btn-default btn-lg' %><br>
        <%= f.label :remember_me %><%= f.check_box :remember_me,  class: "field_checkbox" %>
      </div>
    </div>
  <% end %>

  <div class="row">
  <div class="col-sm-11 col-sm-1">
    <h1> Sign Up<span style="font-size:30px !important;"> for recipes you can eat.</span> </h1>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <div class="row">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.text_field :name, placeholder: "Name", size:30 %>
          <%= f.email_field :email, placeholder:"Email", size:30 %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-11 col-sm-offset-1">
          <%= f.password_field :password, placeholder: "Password, Minimum 8 Characters",size: 30 %>
          <%= f.password_field :password_confirmation, placeholder: "Repeat Password", size:30 %>
          <%= f.submit "Sign up", class: 'btn btn-default btn-lg' %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 ">
          <% @allergies.each do |allergy| %>
            <%= check_box_tag "user[allergy_ids][]", allergy.id %>
           <div class="check_name"> <%= allergy.name %></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-xs-2 col-sm-3">
      <div class="image-container">
        <img src="assets/norman_rockwell_dinner.jpg" alt="Normal Rockwell Image">
        </div>
    </div>

    <div class="col-xs-10 col-sm-9">
    <%=render 'form'%>
   </div>
  </div>
</div>