config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  # devise_for :user, :path => "accounts"

  # root 'devise/sessions#new', as: :unauthenticated_root
#  devise_for :users
  devise_for :users, paths:'users', :controllers => { registrations: 'registrations' }
  resources :welcome, only: :index
  # root 'welcome#index'
  resources :about, only: :index
  # root 'about#index'

  resources :dashboard, only: [:index,:edit]
  authenticated :user do
  root "dashboard#index", as: :authenticated_root
    end
  unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
  end


  # devise_scope :user do
  #   authenticated :user do
  #     root 'home#index', as: :authenticated_root
  #   end
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end

  resources :users, only: [:index], shallow:true do
    resources :recipes, only: [:new,:create,:index]
  end

  resources :recipes, only: [:show,:edit,:update,:destroy] do
      resources :comments, only: [:new,:create]
  end

  resources :comments, only: :destroy
  resources :allergies, only: :index
  resources :foodflags, only: :index
  resources :ingredientflags, only: :index

end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <h2>WICE, <span style="font-size:15px !important;">What I Can Eat App</span></h2>
    <ul class="nav nav-tabs navbar-nav navbar-right">
      <li><%= link_to "Home ", welcome_index_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Dashboard", dashboard_index_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <li>
        <%= link_to "About", about_index_path  %>
        </li>
      <% else %>
        <li>
        <%= link_to "Login", welcome_index_path  %>
        </li>
        <li>
        <%= link_to "About", about_index_path  %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WICEApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class='container-fluid height-full'> <div class='pages'>
    <%= flash_messages %>
    <%= yield %>
  </div>
  </div>

</body>
</html>